security:

    hide_user_not_found: false

    encoders:
        Zayso\User\User:
            id: Zayso\User\UserEncoder

    providers:
        user_provider:
            id: Zayso\User\UserProvider

    role_hierarchy:
        ROLE_USER:  []
        ROLE_ADMIN: [ROLE_USER,ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/
            anonymous: ~
            switch_user: true

            form_login:
                provider:   user_provider
                login_path: user_login
                check_path: user_login_check

                default_target_path: basic_welcome

                username_parameter:  username
                password_parameter:  password

                csrf_parameter:       csrf_token
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   user_logout
                target: basic_welcome

