services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        #tags: ['some_tag']

    App\Basic\:
        resource: '*'

    App\Basic\Index\IndexAction:
        public: true

    App\Basic\Welcome\WelcomeAction:
        tags: ['controller.service_arguments']

